FROM python:3.12-slim

WORKDIR /app
COPY dashboard/requirements.txt ./dashboard/
RUN pip install --no-cache-dir -r dashboard/requirements.txt

COPY db/ ./db/
COPY dashboard/ ./dashboard/
COPY .env* ./

CMD ["uvicorn", "dashboard.app:socket_app", "--host", "0.0.0.0", "--port", "8000"]
